### ISSUE TITLE
the link to paper

### ISSUE THREAD

**Issue by firelight8752** [Luffy03/CISC-R#1]
This seems to be an interesting job. Unfortunately, no papers have been retrieved from Google Academic and Arxiv. 
So where can I find this paper?

**Comment by Luffy03** [comment]
Thanks for your attention to our work! The paper is still under review. We will release our paper and code as soon as possible.

**Comment by firelight8752** [comment]
Great. Do you plan to upload a preprint of your paper on Arxiv?

**Comment by Luffy03** [comment]
> Great. Do you plan to upload a preprint of your paper on Arxiv?

No, sorry for that. But we assume that the paper will be accepted in a few days, we will make it available as soon as possible.

**Comment by firelight8752** [comment]
Thanks.
