### ISSUE TITLE
Why use the label of unlabeled imgs during training

### ISSUE THREAD

**Issue by Rui-Zhou-2** [Luffy03/CISC-R#3]
Hi, for semi-supervised learning, isn't the label of unlabeled images supposed to be unaccessible during training time and only used for evaluation?

https://github.com/Luffy03/CISC-R/blob/2ab013eef265ebcb02c13c9f9e85a889355298b3/train.py#L261

**Comment by Luffy03** [comment]
Hi, many thanks for your kind attention!
As you say, the labels of unlabeled images are supposed to be inaccessible. For semi-training (mode=='semi-train'), we load the generated pseudo labels (mask1) for unlabeled images, please refer to 'dataset/cross.py'.
![image](https://user-images.githubusercontent.com/52514670/230806008-5db4b1c5-64aa-4401-a348-0662d7bb3aea.png)

**Comment by xjjj-hub** [comment]
lock
***@***.***



&nbsp;
https://www.iqiyi.com/v_2g5a5i7gnyk.html?vfm=2008_aldbd&amp;fc=828fb30b722f3164&amp;fv=p_02_01


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Luffy03/CISC-R"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 上午9:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Luffy03/CISC-R] Why use the label of unlabeled imgs during training (Issue #3)





 
Hi, many thanks for your kind attention!
 As you say, the labels of unlabeled images are supposed to be inaccessible. For semi-training (mode=='semi-train'), we load the generated pseudo labels (mask1) for unlabeled images, please refer to 'dataset/cross.py'.

**Comment by Luffy03** [comment]
I will close this issue. Feel free to re-open it if you still have questions.
Thanks for your kind attention again!

**Comment by Rui-Zhou-2** [comment]
Thanks for your reply. Then this seems to calculate the loss between two pseudo labels?
![image](https://user-images.githubusercontent.com/95934070/231194233-79d8423f-2087-44ec-af0f-c881c73a665a.png)

**Comment by Luffy03** [comment]
> Thanks for your reply. Then this seems to calculate the loss between two pseudo labels? ![image](https://user-images.githubusercontent.com/95934070/231194233-79d8423f-2087-44ec-af0f-c881c73a665a.png)

No. The loss is between predictions and pseudo labels of unlabeled images. Please follow Eqn.7 in our paper.
