### ISSUE TITLE
The time cost in training phase

### ISSUE THREAD

**Issue by Hugo-cell111** [Luffy03/CISC-R#4]
Hi! In the paper, selecting the most suitable labeled sample needs to access to the whole labeled dataset. So I wonder if it will take lots of time. Thanks!

**Comment by Luffy03** [comment]
Hi, thanks for your kind and valuable comments!
In SSL, only a few labeled training samples are available. For images containing a specific class (e.g., cat), maybe only 10-20 images need to be selected. In this case, it does not cost lots of time.
