### ISSUE TITLE
关于dataset/cls_txt文件

### ISSUE THREAD

**Issue by FrankYii1** [Luffy03/CISC-R#5]
作者你好，感谢你的工作！
我想把你的代码用到我的自建数据集上，但是我不知道dataset/cls_txt里面的包含类图片的txt文件是怎么得到？

**Comment by Luffy03** [comment]
您好，感谢您对我们工作的关注。
很抱歉我没有提供相关代码。不过当您拥有数据集的标签时，很容易生成相关的txt文件。

**Comment by Luffy03** [comment]
> 作者你好，感谢你的工作！ 我想把你的代码用到我的自建数据集上，但是我不知道dataset/cls_txt里面的包含类图片的txt文件是怎么得到？

在dataset/make_query_txt下，我们提供了部分代码，可见random_select函数用于参考

**Comment by FrankYii1** [comment]
谢谢作者的回复~还想请教您一下，是要对所有的数据集都生成关于类别的txt文件，还是只用对有标签数据生成相应类别的txt文件？

**Comment by Luffy03** [comment]
> 谢谢作者的回复~还想请教您一下，是要对所有的数据集都生成关于类别的txt文件，还是只用对有标签数据生成相应类别的txt文件？

仅对有标签数据。
