### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by Zkx199800** [Luffy03/CISC-R#7]
How to get the 'cls_txt' in the project?

**Comment by Luffy03** [comment]
Hi, to generate 'cls_txt', you need the annotations of labeled set.
If you want to generate 'cls_txt' in your own dataset, you can find the details in the function 'random_select' of 'make_query_txt.py'. .

**Comment by Zkx199800** [comment]
你好，作业已收到，感谢提交！

**Comment by Zkx199800** [comment]
OK, thank you.
